### ISSUE TITLE
Does not work when form has not empty block prefix

### ISSUE THREAD

**Issue by whyte624** [Bee-Lab/BeelabRecaptcha2Bundle#18] opened 2016-11-05 20:14 UTC
I've created a form which has a blockPrefix and added RecaptchaType field to it.
When I handle a request, the 'captcha' field value is `null`.

The workaround for it is as follows:
```
$form = $this->createForm(MyFormType::class);
$data = $request->request->get($form->getName(), []);
$recaptcha = $request->request->get('g-recaptcha-response', '');
$data[$form->get('captcha')->getName()] = $recaptcha;
$request->request->set($form->getName(), $data);
$form->handleRequest($request);
if ($form->isValid()) {
```
which I don't like.

Is there a way to handle a request for named form?

**Comment by garak** [comment] 2016-11-05 21:58
There's no difference between a form with blockPrefix and form without blockPrefix, the latter is simply getting an automatic blockPrefix based on form's name.

**Comment by whyte624** [comment] 2016-11-06 05:12
You are right, it doesn't work without block prefix as well. After `$form->handleRequest($request);` the captcha field is empty. The validator tried to check enjoy value.

**Comment by whyte624** [comment] 2016-11-06 09:27
Latest. 1.2
Symfony  3.1.6

**Comment by garak** [comment] 2016-11-06 09:59
Which version are you using?

**Comment by garak** [comment] 2016-11-06 14:35
Can you provide a way to reproduce your issue?

**Comment by whyte624** [comment] 2016-11-07 15:47
I have a Form with RecaptchaType class as follows:

```
use Beelab\Recaptcha2Bundle\Form\Type\RecaptchaType;
use Beelab\Recaptcha2Bundle\Validator\Constraints\Recaptcha2;
...
$builder->add(
                'captcha',
                RecaptchaType::class,
                [
                    'label' => false,
                    'mapped' => false,
                    'constraints' => new Recaptcha2(),
                ]
            )
```

In controller:
```
    public function giftRequestAction(Request $request)
    {
        $form = $this->createForm(ContactType::class);
        $form->handleRequest($request);
        if ($form->isValid()) {
}
}
```

Form rendered without any customization: `{{ form(form) }}` and `<script src="//www.google.com/recaptcha/api.js"></script>`

Interface works just fine. And after submitting a form I see in request = 
```
$request->request->parameters = [
'contact' => [
'text' => 'Hi!'
], 
'g-recaptcha-response' => '{some hash}'
]
```

And then I get an error that field 'captcha' is invalid.

**Comment by whyte624** [comment] 2016-11-07 15:55
It seems like the problem is there:
\Beelab\Recaptcha2Bundle\Recaptcha\RecaptchaVerifier::verify

In previous versions it tried to validate:
`$recaptchaValue = $this->request->request->get('g-recaptcha-response');`
Now it tries to validate empty value from the field.

**Comment by garak** [comment] 2016-11-07 16:02
Maybe @Th3Mouk can help here?

**Comment by whyte624** [comment] 2016-11-07 16:04
I would suggest to return this way of validating:
`$recaptchaValue = $this->request->request->get('g-recaptcha-response');`
since current validator doesn't actually validates.

**Comment by Th3Mouk** [comment] 2016-11-07 16:11
Yes I have an idea, let me check

**Comment by whyte624** [comment] 2016-11-07 16:45
And now it doesn't work because form has a block prefix. In my case posted data is $_POST = ['contact' => ['text' => 'some text'], 'g-recaptcha-response' => 'hash']; It means that the form value will be empty.

**Comment by garak** [comment] 2016-11-07 17:08
@whyte624 can you confirm that PR proposed by @Th3Mouk is solving your issue?

**Comment by whyte624** [comment] 2016-11-07 17:28
It should work. Is it a temporary solution?

**Comment by Th3Mouk** [comment] 2016-11-07 17:31
Not temporary, the things is we need to handle both issues, with regular usage or harcoded value due to non-configurable input drawed by Google JS

**Comment by whyte624** [comment] 2016-11-07 17:32
OK, we'll see.  Thanks, guys!

**Comment by garak** [comment] 2016-11-07 17:34
@whyte624 try using `1.3.*@dev` in your composer.json and update. Let me know if this is solving. In case, I'll close this and release a new tag.

**Comment by whyte624** [comment] 2016-11-08 07:30
Works fine! Waiting for tag.

**Comment by garak** [comment] 2016-11-08 09:00
Here you are: https://github.com/Bee-Lab/BeelabRecaptcha2Bundle/releases/tag/v1.2.1

**Closed by garak** 2016-11-08 09:00 UTC
